### ISSUE TITLE
Unable to get cities by state when the state name contain the word state

### ISSUE THREAD

**Issue by pmutshipayi** [MartinsOnuoha/countriesNowAPI#110]
When trying to get cities by state, if the state name contains the word `state` the request fail with error  `state not found`

Example 1:

https://countriesnow.space/api/v0.1/countries/state/cities
payload
```JSON
{
    "country": "Micronesia",
    "state": "Pohnpei State"
}
```

Example 1:

https://countriesnow.space/api/v0.1/countries/state/cities
payload
```JSON
{
    "country": "Micronesia",
    "state": "Pohnpei State"
}
```
response:
```JSON
{
    "error": true,
    "msg": "state not found"
}
```
<br /><br /> <br />

Example 2:

https://countriesnow.space/api/v0.1/countries/state/cities

payload

```JSON
{
    "country": "South Africa",
    "state": "free state"
}
``` 
Response:
```JSON
{
    "error": true,
    "msg": "state not found"
}
```

**Comment by MartinsOnuoha** [comment]
Hi @pmutshipayi , Thanks for reporting this bug, apparently we were formatting payload that includes "state". Mostly because not a lot of state names end with "state", I guess we forgot free state was a state (lol). I've opened a new MR to resolve this problem. Feel free to have a look and approve it.
