### ISSUE TITLE
Feature request: Country code as param

### ISSUE THREAD

**Issue by icopp** [MartinsOnuoha/countriesNowAPI#83]
Currently the country name is required, but preferred country names can be inconsistent (for example, see "Viet Nam" vs "Vietnam"). It would be useful to instead allow one of either `country`, `countryCode` (an alias for `countryCodeIso2`), `countryCodeIso2`, or `countryCodeIso3`.

**Comment by MartinsOnuoha** [comment]
Hi @icopp, this makes a lot of sense, If I understand you correctly: since we are aggregating data from multiple data sources there are chances of having variations in the naming, and the best possible solution for this would be to make the country name optional and provide another query param that a little more consistent like the `Iso` or `Iso3`

**Comment by icopp** [comment]
Yes, exactly.

**Comment by MartinsOnuoha** [comment]
Sounds great, which endpoints would you suggest we add this feature to?

**Comment by MartinsOnuoha** [comment]
@icopp Have a look at the open MR, looks good?

**Comment by icopp** [comment]
Sorry about the delay, but the gist there all looks good to me.

**Comment by MartinsOnuoha** [comment]
Great thanks
